# Generated by Django 4.2.16 on 2025-07-20 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('profit_loss', 'Profit & Loss'), ('expense_summary', 'Expense Summary')], help_text='Type of financial report', max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV')], default='pdf', help_text='Format of the generated report', max_length=5)),
                ('start_date', models.DateField(help_text='Start date for the report period')),
                ('end_date', models.DateField(help_text='End date for the report period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for background processing', max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated report file', max_length=500, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters used for report generation')),
                ('error_message', models.TextField(blank=True, help_text='Error message if report generation failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when report generation was completed', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
