FROM node:18-alpine

WORKDIR /app

COPY package.json.minimal /app/package.json
RUN npm install

COPY public /app/public
COPY src/index.js /app/src/
COPY src/index.css /app/src/

EXPOSE 3000
CMD ["npm", "start"]
