release: bash release.sh
web: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
worker: celery -A backend worker --loglevel=info --concurrency=2
beat: celery -A backend beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
