# Generated by Django 4.2.16 on 2025-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_clients',
            field=models.IntegerField(default=5),
        ),
    ]
