"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv(os.path.join(Path(__file__).resolve().parent.parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', "django-insecure-spylrai(f%q3a@2zb0a(zz5evqf3&8dj*5tp7(8y9zxrkk_16k")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Add Heroku domain to allowed hosts
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,.herokuapp.com,testserver').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "drf_yasg",
    "rest_framework_simplejwt",
    "django_celery_beat",  # For periodic tasks
    
    # Project apps
    "accounts",
    "receipts",
    "subscriptions",
    "reports",  # Added financial reports app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Add Whitenoise for static files
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # Add CORS middleware before CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configure database for Heroku
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True if os.environ.get('DATABASE_SSL', 'False') == 'True' else False
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-gb"  # Changed to British English

TIME_ZONE = "Europe/London"  # Changed to UK timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Whitenoise configuration for static file serving in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files - use S3 for Heroku deployment
DEFAULT_FILE_STORAGE = os.environ.get(
    'DEFAULT_FILE_STORAGE',
    'django.core.files.storage.FileSystemStorage'
)

# For local development
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 15 * 1024 * 1024  # 15MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# S3 settings (when enabled)
if DEFAULT_FILE_STORAGE == 'storages.backends.s3boto3.S3Boto3Storage':
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'eu-west-2')
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    # S3 static settings
    STATIC_LOCATION = 'static'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    # S3 media settings
    MEDIA_LOCATION = 'media'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{MEDIA_LOCATION}/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = 'accounts.Account'

# CORS settings
CORS_ALLOW_CREDENTIALS = True
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', 'http://localhost:3000').split(',')

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Set secure cookies in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True if os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True' else False
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,  # Increased from 20 to 100 for better UX
    'EXCEPTION_HANDLER': 'backend.exceptions.custom_exception_handler',
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# Veryfi API settings
VERYFI_CLIENT_ID = os.environ.get('VERYFI_CLIENT_ID', '')
VERYFI_CLIENT_SECRET = os.environ.get('VERYFI_CLIENT_SECRET', '')
VERYFI_USERNAME = os.environ.get('VERYFI_USERNAME', '')
VERYFI_API_KEY = os.environ.get('VERYFI_API_KEY', '')
VERYFI_ENVIRONMENT_URL = os.environ.get('VERYFI_ENVIRONMENT_URL', 'https://api.veryfi.com/')

# Stripe settings
STRIPE_API_PUBLISHABLE_KEY = os.environ.get('STRIPE_API_PUBLISHABLE_KEY', '')
STRIPE_API_SECRET_KEY = os.environ.get('STRIPE_API_SECRET_KEY', '')
STRIPE_SECRET_KEY = STRIPE_API_SECRET_KEY  # Alias for service compatibility
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
STRIPE_API_VERSION = os.environ.get('STRIPE_API_VERSION', '2023-10-16')

# Frontend URLs for Stripe redirects
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')
STRIPE_SUCCESS_URL = os.environ.get('STRIPE_SUCCESS_URL', f'{FRONTEND_URL}/subscriptions/success')
STRIPE_CANCEL_URL = os.environ.get('STRIPE_CANCEL_URL', f'{FRONTEND_URL}/subscriptions/cancel')

# Subscription price IDs
STRIPE_BASIC_PRICE_ID = os.environ.get('STRIPE_BASIC_PRICE_ID', '')
STRIPE_PREMIUM_PRICE_ID = os.environ.get('STRIPE_PREMIUM_PRICE_ID', '')
STRIPE_PLATINUM_PRICE_ID = os.environ.get('STRIPE_PLATINUM_PRICE_ID', '')

# Email settings
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend'
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@smartaccounting.com')

# AI Vision API settings
OPENAI_API_KEY = os.environ.get('OPEN_AI_API_KEY', '')
OPENAI_VISION_MODEL = os.environ.get('OPENAI_VISION_MODEL', 'gpt-4o')  # GPT-4o is the top vision API
XAI_API_KEY = os.environ.get('XAI_API_KEY', '')
VISION_API_PRIMARY = os.environ.get('VISION_API_PRIMARY', 'openai')
VISION_API_FALLBACK = os.environ.get('VISION_API_FALLBACK', 'xai')
VISION_API_TIMEOUT = int(os.environ.get('VISION_API_TIMEOUT', 30))
VISION_API_MAX_RETRIES = int(os.environ.get('VISION_API_MAX_RETRIES', 3))

# Performance optimization settings
VISION_API_ENABLE_CACHING = os.environ.get('VISION_API_ENABLE_CACHING', 'True').lower() == 'true'
VISION_API_ENABLE_OPTIMIZATION = os.environ.get('VISION_API_ENABLE_OPTIMIZATION', 'True').lower() == 'true'
VISION_API_ENABLE_RATE_LIMITING = os.environ.get('VISION_API_ENABLE_RATE_LIMITING', 'True').lower() == 'true'
VISION_API_CACHE_TIMEOUT = int(os.environ.get('VISION_API_CACHE_TIMEOUT', 3600))  # 1 hour
VISION_API_RATE_LIMIT = int(os.environ.get('VISION_API_RATE_LIMIT', 60))  # per minute
VISION_API_MAX_RETRIES = int(os.environ.get('VISION_API_MAX_RETRIES', 3))

# Enhanced OpenAI settings from best practices
ENABLE_UK_RECEIPT_ENHANCEMENT = os.environ.get('ENABLE_UK_RECEIPT_ENHANCEMENT', 'True').lower() == 'true'
OPENAI_TEMPERATURE = float(os.environ.get('OPENAI_TEMPERATURE', '0'))  # Deterministic output
OPENAI_SEED = int(os.environ.get('OPENAI_SEED', '42'))  # Reproducible results
OPENAI_MAX_TOKENS = int(os.environ.get('OPENAI_MAX_TOKENS', '2000'))  # Default token limit

# v0.5 Enhanced processing settings
OPENAI_V5_ENABLE_SEGMENTATION = os.environ.get('OPENAI_V5_ENABLE_SEGMENTATION', 'True').lower() == 'true'
OPENAI_V5_MAX_MEGAPIXELS = int(os.environ.get('OPENAI_V5_MAX_MEGAPIXELS', '12'))  # Cost guard
OPENAI_V5_TILE_HEIGHT = int(os.environ.get('OPENAI_V5_TILE_HEIGHT', '1500'))  # px per segment
OPENAI_V5_TILE_OVERLAP = int(os.environ.get('OPENAI_V5_TILE_OVERLAP', '200'))  # px overlap
OPENAI_V5_ENABLE_GROUNDING = os.environ.get('OPENAI_V5_ENABLE_GROUNDING', 'True').lower() == 'true'

# Swagger settings
SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },
    'USE_SESSION_AUTH': False,
    'JSON_EDITOR': True,
}

# ===============================================
# HEROKU PERFORMANCE OPTIMIZATIONS
# ===============================================

# Celery Configuration for Background Tasks
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Performance settings for Celery
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100
CELERY_TASK_TIME_LIMIT = 720  # 12 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 600  # 10 minutes
CELERY_RESULT_EXPIRES = 3600  # 1 hour

# Task routing
CELERY_TASK_ROUTES = {
    'receipts.tasks.process_receipt_task': {'queue': 'ocr_processing'},
    'receipts.tasks.batch_process_receipts': {'queue': 'ocr_batch'},
    'receipts.tasks.cleanup_temp_files': {'queue': 'maintenance'},
}

# HTTP/2 and Connection Pooling Settings
HTTP_CLIENT_SETTINGS = {
    'http2': True,
    'max_keepalive_connections': 20,
    'max_connections': 100,
    'keepalive_expiry': 30.0,
    'connect_timeout': 10.0,
    'read_timeout': 60.0,
    'write_timeout': 10.0,
    'pool_timeout': 5.0,
}

# Concurrent Processing Limits
MAX_CONCURRENT_OCR_REQUESTS = int(os.environ.get('MAX_CONCURRENT_OCR_REQUESTS', '8'))
THREAD_POOL_MAX_WORKERS = int(os.environ.get('THREAD_POOL_MAX_WORKERS', '16'))

# Performance Monitoring
ENABLE_PERFORMANCE_MONITORING = os.environ.get('ENABLE_PERFORMANCE_MONITORING', 'True').lower() == 'true'
PERFORMANCE_STATS_RETENTION_DAYS = int(os.environ.get('PERFORMANCE_STATS_RETENTION_DAYS', '7'))

# Heroku-specific optimizations
if 'DYNO' in os.environ:
    # Running on Heroku
    HEROKU_DEPLOYMENT = True
    
    # Optimize for Heroku's ephemeral filesystem
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    
    # Use whitenoise for static files
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    
    # Heroku Postgres optimization
    DATABASES['default']['CONN_MAX_AGE'] = 600
    DATABASES['default']['OPTIONS'] = {
        'MAX_CONNS': 20,
        'OPTIONS': {
            'server_side_binding': True,
        }
    }
else:
    HEROKU_DEPLOYMENT = False
