# Generated by Django 4.2.16 on 2025-07-20 07:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Legal name of the client company', max_length=255)),
                ('contact_person', models.CharField(help_text='Primary contact person at the client company', max_length=255)),
                ('email', models.EmailField(help_text='Primary email address for the client', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Primary phone number', max_length=20, null=True)),
                ('address_line_1', models.CharField(help_text='Street address', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Additional address information', max_length=255, null=True)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal code', max_length=20, validators=[django.core.validators.RegexValidator(flags=0, message='Enter a valid UK postcode (e.g., SW1A 1AA)', regex='^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z]{2}$')])),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('vat_number', models.CharField(blank=True, help_text='VAT registration number if applicable', max_length=15, null=True, validators=[django.core.validators.RegexValidator(flags=0, message='Enter a valid UK VAT number (e.g., GB123456789)', regex='^GB[0-9]{9}$|^GB[0-9]{12}$|^GBGD[0-9]{3}$|^GBHA[0-9]{3}$')])),
                ('business_type', models.CharField(choices=[('sole_trader', 'Sole Trader'), ('limited_company', 'Limited Company'), ('partnership', 'Partnership'), ('llp', 'Limited Liability Partnership'), ('other', 'Other')], default='sole_trader', help_text='Type of business entity', max_length=20)),
                ('companies_house_number', models.CharField(blank=True, help_text='Companies House registration number (for limited companies)', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this client is currently active')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the client', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When the client was deactivated', null=True)),
                ('accounting_firm', models.ForeignKey(help_text='The accounting firm that manages this client', limit_choices_to={'user_type': 'accounting_firm'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['company_name'],
                'unique_together': {('accounting_firm', 'company_name')},
            },
        ),
    ]
