# Generated by Django 4.2.16 on 2025-07-20 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Client's first name", max_length=150)),
                ('last_name', models.CharField(help_text="Client's last name", max_length=150)),
                ('email', models.EmailField(help_text="Client's email address", max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text="Client's phone number", max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, help_text="Client's company name", max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, help_text='Type of business', max_length=100, null=True)),
                ('vat_number', models.CharField(blank=True, help_text='VAT registration number', max_length=50, null=True)),
                ('company_registration_number', models.CharField(blank=True, help_text='Company registration number', max_length=50, null=True)),
                ('address_line_1', models.CharField(blank=True, help_text='First line of address', max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, help_text='Second line of address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('county', models.CharField(blank=True, help_text='County', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal code', max_length=20, null=True)),
                ('country', models.CharField(default='United Kingdom', help_text='Country', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the client', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the client is active or archived')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the client was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the client was last updated')),
                ('accounting_firm', models.ForeignKey(help_text='Accounting firm that manages this client', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
                'unique_together': {('accounting_firm', 'email')},
            },
        ),
    ]
