# Generated by Django 4.2.16 on 2025-07-20 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Client's full name or company name", max_length=255)),
                ('email', models.EmailField(blank=True, help_text="Client's email address", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text="Client's phone number", max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text="Client's full address", null=True)),
                ('tax_reference', models.CharField(blank=True, help_text="Client's tax reference number", max_length=50, null=True)),
                ('vat_number', models.CharField(blank=True, help_text="Client's VAT registration number", max_length=50, null=True)),
                ('business_type', models.CharField(blank=True, choices=[('individual', 'Individual'), ('sole_trader', 'Sole Trader'), ('partnership', 'Partnership'), ('limited_company', 'Limited Company'), ('llp', 'Limited Liability Partnership'), ('charity', 'Charity'), ('other', 'Other')], help_text='Type of business entity', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(help_text='The accounting firm that manages this client', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name', 'firm'), name='unique_client_name_per_firm', violation_error_message='A client with this name already exists for this firm.'),
        ),
    ]
