# Generated by Django 4.2.16 on 2025-07-20 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Office Supplies', 'Client Consulting')", max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this is an income or expense category', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of the category', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='System-created default category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this category', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
        # Rename the old category field to old_category temporarily
        migrations.RenameField(
            model_name='transaction',
            old_name='category',
            new_name='old_category',
        ),
        # Add the new category field (nullable for now)
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Custom category for this transaction', null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='receipts.category'),
        ),
    ]
