# Generated by Django 4.2.16 on 2025-07-20 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this is an income or expense category', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is a default system category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of the category. Null for default system categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
                'unique_together': {('owner', 'name', 'type')},
            },
        ),
    ]
