# Generated by Django 4.2.16 on 2025-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='api_responses',
            field=models.JSONField(blank=True, default=dict, help_text='Stores responses from all APIs used'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Cleaned and standardized extracted data'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='fallback_api_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='primary_api_used',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processing_errors',
            field=models.JSONField(blank=True, default=list, help_text='Processing errors and retry attempts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processing_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_cost_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='APIUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('api_name', models.CharField(max_length=50)),
                ('requests_count', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('failed_requests', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('average_response_time', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', 'api_name'],
                'unique_together': {('date', 'api_name')},
            },
        ),
    ]
