# Generated by Django 4.2.16 on 2025-07-20 07:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_name', models.CharField(help_text='Descriptive name for the report', max_length=200)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Date Range'), ('vat_return', 'VAT Return'), ('profit_loss', 'Profit & Loss Statement'), ('expense_summary', 'Expense Summary'), ('income_summary', 'Income Summary')], help_text='Type of financial report', max_length=50)),
                ('period_start', models.DateField(help_text='Start date for the report period')),
                ('period_end', models.DateField(help_text='End date for the report period')),
                ('file_path', models.CharField(blank=True, help_text='Path to generated report file', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('Excel', 'Excel'), ('JSON', 'JSON')], default='PDF', help_text='Export format for the report', max_length=10)),
                ('parameters', models.JSONField(blank=True, help_text='Parameters used to generate the report (categories, filters, etc.)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current status of report generation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(blank=True, help_text='When the report was successfully generated', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the report file expires and should be cleaned up', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Category name (e.g., 'Office Supplies')", max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], help_text='Whether this category is for income or expenses', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description for the category', null=True)),
                ('is_tax_deductible', models.BooleanField(default=False, help_text='Whether expenses in this category are tax deductible for UK tax purposes')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Default VAT rate for this category (percentage, e.g., 20.00 for 20%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_default', models.BooleanField(default=False, help_text='System default categories that cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of custom categories. Null for system default categories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Transaction category for organization and tax reporting', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='receipts.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'type', 'owner'), name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('name', 'type'), name='unique_default_category'),
        ),
    ]
