# Generated by Django 4.2.16 on 2025-07-20 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import receipts.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='assigned_client',
            field=models.ForeignKey(blank=True, help_text='Client this document is assigned to (for accounting firm users)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='extracted_data',
            field=models.JSONField(blank=True, help_text='Structured data extracted from OCR text', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Raw OCR text extracted from the document', null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(help_text='Accepted formats: JPEG, PNG, PDF, HEIC. Maximum size: 10MB.', upload_to='receipts/', validators=[receipts.validators.validate_document_file]),
        ),
    ]
