# Generated by Django 4.2.16 on 2025-07-20 07:02

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """
    Create default categories for income and expenses.
    """
    Category = apps.get_model('receipts', 'Category')
    
    # Default expense categories (based on existing Transaction categories)
    expense_categories = [
        ('Office Supplies', 'Stationery, office equipment, and supplies'),
        ('Travel', 'Business travel expenses including flights, hotels, and transport'),
        ('Meals & Entertainment', 'Business meals, client entertainment, and hospitality'),
        ('Utilities', 'Electricity, gas, water, internet, and phone bills'),
        ('Rent', 'Office rent, warehouse rent, and property costs'),
        ('Software & Subscriptions', 'Software licenses, SaaS subscriptions, and digital tools'),
        ('Hardware & Equipment', 'Computer hardware, machinery, and business equipment'),
        ('Professional Services', 'Legal fees, accounting, consulting, and professional advice'),
        ('Marketing & Advertising', 'Advertising spend, marketing campaigns, and promotional materials'),
        ('Insurance', 'Business insurance premiums and coverage'),
        ('Training & Development', 'Employee training, courses, and professional development'),
        ('Bank Charges', 'Bank fees, transaction charges, and financial service costs'),
        ('Other', 'Miscellaneous business expenses not categorized elsewhere'),
    ]
    
    # Default income categories
    income_categories = [
        ('Sales Revenue', 'Revenue from product or service sales'),
        ('Consulting Revenue', 'Income from consulting and advisory services'),
        ('Interest Income', 'Interest earned on business accounts and investments'),
        ('Rental Income', 'Income from property rentals or equipment leasing'),
        ('Commission Income', 'Commission and referral fees received'),
        ('Grant Income', 'Government grants and funding received'),
        ('Investment Income', 'Dividends and investment returns'),
        ('Other Income', 'Miscellaneous income not categorized elsewhere'),
    ]
    
    # Create expense categories
    for name, description in expense_categories:
        Category.objects.get_or_create(
            name=name,
            type='expense',
            defaults={
                'description': description,
                'is_default': True,
                'owner': None,  # Default categories have no owner
            }
        )
    
    # Create income categories
    for name, description in income_categories:
        Category.objects.get_or_create(
            name=name,
            type='income',
            defaults={
                'description': description,
                'is_default': True,
                'owner': None,  # Default categories have no owner
            }
        )


def remove_default_categories(apps, schema_editor):
    """
    Remove default categories (for migration rollback).
    """
    Category = apps.get_model('receipts', 'Category')
    Category.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_category'),
    ]

    operations = [
        migrations.RunPython(
            create_default_categories,
            remove_default_categories,
        ),
    ]
