# Generated by Django 4.2.16 on 2025-07-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_api_responses_receipt_extracted_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='api_responses',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='fallback_api_used',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='primary_api_used',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='processing_time_seconds',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total_cost_usd',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='veryfi_document_id',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='veryfi_response_data',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_tax_deductible',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vat_amount',
        ),
        migrations.AddField(
            model_name='apiusagestats',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipt',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Performance data: {processing_time, cost_usd, token_usage, segments_processed}'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='apiusagestats',
            name='api_name',
            field=models.CharField(default='openai', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict, help_text='Flat semantic receipt data: {vendor, date, total, tax, type, currency}'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='processing_errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('meals', 'Meals & Entertainment'), ('travel', 'Travel'), ('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('software', 'Software'), ('hardware', 'Hardware'), ('marketing', 'Marketing'), ('professional_services', 'Professional Services'), ('rent', 'Rent'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
