# Generated by Django 4.2.16 on 2025-07-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_report_category_alter_transaction_category_and_more'),
    ]

    operations = [
    ]
