# Generated by Django 4.2.16 on 2025-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_remove_receipt_api_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cloudinary_display_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cloudinary_thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
