# Generated by Django 4.2.16 on 2025-07-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_migrate_default_categories'),
    ]

    operations = [
        # Remove the old category field
        migrations.RemoveField(
            model_name='transaction',
            name='old_category',
        ),
        # Make the new category field required
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(help_text='Custom category for this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='receipts.category'),
        ),
    ]
