name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements/production.txt
      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile.backend -t smart-accounting-backend:latest .
      # Add your deployment steps here (e.g., push to AWS ECR, deploy to ECS/EC2)
      - name: Deploy to AWS (placeholder)
        run: echo "Add deployment scripts here."
